# Auto-generated by gui.spec at build time. Do not edit manually.
# Sets GAMECUT_VERSION before any app module is imported so that
# backend/services/updater.py reads the correct version.
import os
os.environ.setdefault("GAMECUT_VERSION", "0.1.0")
